### ISSUE TITLE
Windows Server 2019 support ?

### ISSUE THREAD

**Issue by mankaf** [EFTEC/Cyberarms#11]
Hey Guys, 

I would like to thank you for the great job, I wanted to ask if you plan to add support for Windows Server 2019 ?

I tried to run the program after running the installer with no error.

I end up with exception HRESULT 0x8007007E regarding SQLite.interop.dll

![image](https://user-images.githubusercontent.com/16303901/72998705-94767480-3dfe-11ea-907c-8f829a80b5ac.png)

Replacing the DLLs from github files did not solve the issue, maybe a different sqlite package could work ?? could you give me a hint ?

The error text itself:

> ************** Exception Text **************
> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could > not be found. (Exception from HRESULT: 0x8007007E)
>   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
>   at System.Data.SQLite.SQLite3.StaticIsInitialized()
>   at System.Data.SQLite.SQLiteLog.Initialize()
>   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean 
> parseViaFramework)
>   at Cyberarms.IntrusionDetection.Shared.Database.Configure(String directory)
>   at Cyberarms.IntrusionDetection.Admin.SplashScreen.StartupComponents()
>   at Cyberarms.IntrusionDetection.Admin.SplashScreen.t_Tick(Object sender, EventArgs e)
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr > lparam)
>
>
> ************** Loaded Assemblies **************
> mscorlib
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3468.0 built by: NET472REL1LAST_C
>    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> IntrusionDetectionAdmin
>    Assembly Version: 2.2.0.0
>    Win32 Version: 2.2.0
>    CodeBase: 
> file:///C:/Program%20Files/Cyberarms/Cyberarms%20Intrusion%20Detection/IntrusionDetectionAdmin.exe
> ----------------------------------------
> System.Windows.Forms
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>    CodeBase: 
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
>    CodeBase: 
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>    CodeBase: 
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>    CodeBase: 
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3570.0 built by: NET472REL1LAST_B
>    CodeBase: > file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>    CodeBase: > file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Cyberarms.IntrusionDetection.Shared
>    Assembly Version: 2.2.0.0
>    Win32 Version: 2.2.0
>    CodeBase: > file:///C:/Program%20Files/Cyberarms/Cyberarms%20Intrusion%20Detection/Cyberarms.IntrusionD> etection.Shared.DLL
> ----------------------------------------
> System.Data.SQLite
>    Assembly Version: 1.0.84.0
>    Win32 Version: 1.0.84.0
>    CodeBase: 
>  file:///C:/Program%20Files/Cyberarms/Cyberarms%20Intrusion%20Detection/System.Data.SQLite.DLL
> ----------------------------------------
> System.Data
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
>    CodeBase: 
> file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/>System.Data.dll
> ----------------------------------------
> System.Transactions
>    Assembly Version: 4.0.0.0
>    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
>    CodeBase: 
> file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c5619> 34e089/System.Transactions.dll
> ----------------------------------------

If you need any further details or provide some additional logs, feel free to contact me, I will try my best to provide everything needed.

Best Regards 
Miroslav

**Comment by maxemilian** [comment]
Hi Miroslav

 

This is a known error (not a bug). You need to run the «repair» on C++ during the installation (don’t skip the message that C++ is already installed). 

The problem is caused by the internal SQLite library which might be replaced in an upcoming version

 

Best regards

 

 

Max

 

 

Maxemilian Hilbrand (Software & Systeme)




CH: +41 71 511 722 0
AT (mobile): +43 660 703 92 54
 <mailto:maxemilian.hilbrand@isicore.com> maxemilian.hilbrand@isicore.com


isicore AG • Unterlettenstrasse 14 • CH-9443 Widnau
Gerichtsstandort CH-9450 Altstätten, UID CHE-110.354.078
Verwaltungsratspräsident: Maxemilian Hilbrand

 

isicore GmbH • AT-6820 Frastanz

Gerichtsstandort AT-6800 Feldkirch, UID ATU74847339

Geschäftsführung: Nora Kuhn 

 <http://www.isicore.com/> www.isicore.com I   <mailto:info@isicore.com> info@isicore.com

 

 

 

Von: mankaf <notifications@github.com> 
Gesendet: Donnerstag, 23. Januar 2020 16:54
An: EFTEC/Cyberarms <Cyberarms@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [EFTEC/Cyberarms] Windows Server 2019 support ? (#11)

 

Hey Guys,

I would like to thank you for the great job, I wanted to ask if you plan to add support for Windows Server 2019 ?

I tried to run the program after running the installer with no error.

I end up with exception HRESULT 0x8007007E regarding SQLite.interop.dll

 <https://user-images.githubusercontent.com/16303901/72998705-94767480-3dfe-11ea-907c-8f829a80b5ac.png> 

Replacing the DLLs from github files did not solve the issue, maybe a different sqlite package could work ?? could you give me a hint ?

The error text itself:

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could > not be found. (Exception from HRESULT: 0x8007007E)
at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
at System.Data.SQLite.SQLite3.StaticIsInitialized()
at System.Data.SQLite.SQLiteLog.Initialize()
at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean
parseViaFramework)
at Cyberarms.IntrusionDetection.Shared.Database.Configure(String directory)
at Cyberarms.IntrusionDetection.Admin.SplashScreen.StartupComponents()
at Cyberarms.IntrusionDetection.Admin.SplashScreen.t_Tick(Object sender, EventArgs e)
at System.Windows.Forms.Timer.OnTick(EventArgs e)
at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr > lparam)


************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3468.0 built by: NET472REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll


IntrusionDetectionAdmin
Assembly Version: 2.2.0.0
Win32 Version: 2.2.0
CodeBase:
file:///C:/Program%20Files/Cyberarms/Cyberarms%20Intrusion%20Detection/IntrusionDetectionAdmin.exe


System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll


System
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll


System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll


System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll


System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3570.0 built by: NET472REL1LAST_B
CodeBase: > file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll


System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
CodeBase: > file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll


Cyberarms.IntrusionDetection.Shared
Assembly Version: 2.2.0.0
Win32 Version: 2.2.0
CodeBase: > file:///C:/Program%20Files/Cyberarms/Cyberarms%20Intrusion%20Detection/Cyberarms.IntrusionD> etection.Shared.DLL


System.Data.SQLite
Assembly Version: 1.0.84.0
Win32 Version: 1.0.84.0
CodeBase:
file:///C:/Program%20Files/Cyberarms/Cyberarms%20Intrusion%20Detection/System.Data.SQLite.DLL


System.Data
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/ <file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/%3eSystem.Data.dll> >System.Data.dll


System.Transactions
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c5619> 34e089/System.Transactions.dll


If you need any further details or provide some additional logs, feel free to contact me, I will try my best to provide everything needed.

Best Regards
Miroslav
